=== carlosthe19916/windup/config-xml/schema/windup-jboss-labelset.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://windup.jboss.org/schema/jboss-labelset" xmlns="http://windup.jboss.org/schema/jboss-labelset" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <!-- Root element for Windup tests labels. -->
    <xs:element name="labeltest">
        <xs:annotation>
            <xs:documentation>Root element of Windup labels test.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="labelset" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="id"/>
        </xs:complexType>
    </xs:element>

    <!-- Root element. -->
    <xs:element name="labelset">
        <xs:annotation>
            <xs:documentation>Root element of Windup labelset.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="labels" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="label" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional" />
            <xs:attribute type="xs:integer" name="priority" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="label">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="supported" type="tags" minOccurs="0" maxOccurs="1"/>
            <xs:element name="unsuitable" type="tags" minOccurs="0" maxOccurs="1"/>
            <xs:element name="neutral" type="tags" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="required" />
    </xs:complexType>

    <xs:complexType name="tags">
        <xs:sequence>
            <xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== carlosthe19916/windup/config-xml/tests/src/test/resources/labeltestxml/Test1.windup.label.xml
<?xml version="1.0" encoding="UTF-8"?>
<labelset id="testlabelprovider1"
          priority="1"
          xmlns="http://windup.jboss.org/schema/jboss-labelset"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://windup.jboss.org/schema/jboss-labelset http://windup.jboss.org/schema/jboss-labelset/windup-jboss-labelset.xsd">
    <labels>
        <label id="label1">
            <name>Label1</name>
            <description>Label1 test</description>
            <supported>
                <tag>tag1</tag>
            </supported>
            <unsuitable>
                <tag>tag2</tag>
                <tag>tag3</tag>
            </unsuitable>
            <neutral>
                <tag>tag4</tag>
                <tag>tag5</tag>
                <tag>tag6</tag>
            </neutral>
        </label>
        <label id="label2">
            <name>Label2</name>
            <description>Label2 test</description>
            <supported>
                <tag>tag7</tag>
            </supported>
            <unsuitable>
                <tag>tag8</tag>
            </unsuitable>
        </label>
    </labels>
</labelset>

=== carlosthe19916/windup/config-xml/src/test/label-resources/test-labelset-without-priority.windup.xml
<?xml version="1.0" encoding="UTF-8"?>
<labelset id="core_labels"
          xmlns="http://windup.jboss.org/schema/jboss-labelset"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://windup.jboss.org/schema/jboss-labelset http://windup.jboss.org/schema/jboss-labelset/windup-jboss-labelset.xsd">
    <labels>
        <label id="label1">
            <name>label1</name>
            <description>label1 description</description>
            <supported>
                <tag>tagA</tag>
                <tag>tagAA</tag>
            </supported>
            <unsuitable>
                <tag>tagB</tag>
                <tag>tagBB</tag>
            </unsuitable>
            <neutral>
                <tag>tagC</tag>
                <tag>tagCC</tag>
            </neutral>
        </label>
        <label id="label2">
            <name>label2</name>
            <description>label2 description</description>
            <supported>
                <tag>tag1</tag>
                <tag>tag11</tag>
            </supported>
            <unsuitable>
                <tag>tag2</tag>
                <tag>tag22</tag>
            </unsuitable>
            <neutral>
                <tag>tag3</tag>
                <tag>tag33</tag>
            </neutral>
        </label>
    </labels>
</labelset>

=== carlosthe19916/windup/tests/src/test/xml/rules/test.windup.label.xml
<?xml version="1.0" encoding="UTF-8"?>
<labelset id="custom_labels"
          xmlns="http://windup.jboss.org/schema/jboss-labelset"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://windup.jboss.org/schema/jboss-labelset http://windup.jboss.org/schema/jboss-labelset/windup-jboss-labelset.xsd">
    <labels>
        <label id="target1">
            <name>Target1</name>
            <description>Custom target runtime 2</description>
            <supported>
                <tag>EJB*</tag>
            </supported>
            <unsuitable>
                <tag>WebLogic*</tag>
            </unsuitable>
            <neutral>
                <tag>Maven XML*</tag>
                <tag>Web XML*</tag>
            </neutral>
        </label>
        <label id="target2">
            <name>Target2</name>
            <description>Custom target runtime 1</description>
            <supported>
                <tag>WebLogic*</tag>
            </supported>
            <unsuitable>
                <tag>JPA*</tag>
            </unsuitable>
            <neutral>
                <tag>Maven XML*</tag>
                <tag>Web XML*</tag>
            </neutral>
        </label>
        <label id="target3">
            <name>Target3</name>
            <description>Custom target runtime 3</description>
            <supported>
                <tag>WebLogic*</tag>
                <tag>EJB*</tag>
            </supported>
            <unsuitable>
                <tag>JPA*</tag>
            </unsuitable>
            <neutral>
                <tag>Maven XML*</tag>
                <tag>Web XML*</tag>
                <tag>Manifest</tag>
                <tag>Properties</tag>
            </neutral>
        </label>
    </labels>
</labelset>
